FROM ubuntu:mantic
ENV LANG ru_RU.UTF-8  
ENV LANGUAGE ru_RU:en 
ENV LC_ALL ru_RU.UTF-8 
RUN apt update
RUN apt install -y locales language-pack-ru wget mc
RUN wget http://www.lib.ru/CARROLL/alice.txt
COPY script.sh /
CMD /bin/bash